apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: static-web
  namespace: devops
  labels:
    app: static-web
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: web
          image: cr.yandex/crp44igmlqftj6a9bep0/devops:1.0.0
          ports:
            - name: http
              containerPort: 5103
              protocol: TCP
