apiVersion: v1
kind: Service
metadata:
  name: static-web-service
  namespace: devops
  labels:
    app: static-web
spec:
  selector:
    app: static-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5103

